// Code generated by ent, DO NOT EDIT.

package adminbillingrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldDeletedAt, v))
}

// PersonName applies equality check predicate on the "person_name" field. It's identical to PersonNameEQ.
func PersonName(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldPersonName, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldSource, v))
}

// Cost applies equality check predicate on the "cost" field. It's identical to CostEQ.
func Cost(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldCost, v))
}

// Profit applies equality check predicate on the "profit" field. It's identical to ProfitEQ.
func Profit(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldProfit, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldOccurredAt, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldNote, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotNull(FieldDeletedAt))
}

// PersonNameEQ applies the EQ predicate on the "person_name" field.
func PersonNameEQ(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldPersonName, v))
}

// PersonNameNEQ applies the NEQ predicate on the "person_name" field.
func PersonNameNEQ(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldPersonName, v))
}

// PersonNameIn applies the In predicate on the "person_name" field.
func PersonNameIn(vs ...string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldPersonName, vs...))
}

// PersonNameNotIn applies the NotIn predicate on the "person_name" field.
func PersonNameNotIn(vs ...string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldPersonName, vs...))
}

// PersonNameGT applies the GT predicate on the "person_name" field.
func PersonNameGT(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldPersonName, v))
}

// PersonNameGTE applies the GTE predicate on the "person_name" field.
func PersonNameGTE(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldPersonName, v))
}

// PersonNameLT applies the LT predicate on the "person_name" field.
func PersonNameLT(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldPersonName, v))
}

// PersonNameLTE applies the LTE predicate on the "person_name" field.
func PersonNameLTE(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldPersonName, v))
}

// PersonNameContains applies the Contains predicate on the "person_name" field.
func PersonNameContains(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldContains(FieldPersonName, v))
}

// PersonNameHasPrefix applies the HasPrefix predicate on the "person_name" field.
func PersonNameHasPrefix(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldHasPrefix(FieldPersonName, v))
}

// PersonNameHasSuffix applies the HasSuffix predicate on the "person_name" field.
func PersonNameHasSuffix(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldHasSuffix(FieldPersonName, v))
}

// PersonNameEqualFold applies the EqualFold predicate on the "person_name" field.
func PersonNameEqualFold(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEqualFold(FieldPersonName, v))
}

// PersonNameContainsFold applies the ContainsFold predicate on the "person_name" field.
func PersonNameContainsFold(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldContainsFold(FieldPersonName, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldContainsFold(FieldSource, v))
}

// CostEQ applies the EQ predicate on the "cost" field.
func CostEQ(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldCost, v))
}

// CostNEQ applies the NEQ predicate on the "cost" field.
func CostNEQ(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldCost, v))
}

// CostIn applies the In predicate on the "cost" field.
func CostIn(vs ...float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldCost, vs...))
}

// CostNotIn applies the NotIn predicate on the "cost" field.
func CostNotIn(vs ...float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldCost, vs...))
}

// CostGT applies the GT predicate on the "cost" field.
func CostGT(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldCost, v))
}

// CostGTE applies the GTE predicate on the "cost" field.
func CostGTE(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldCost, v))
}

// CostLT applies the LT predicate on the "cost" field.
func CostLT(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldCost, v))
}

// CostLTE applies the LTE predicate on the "cost" field.
func CostLTE(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldCost, v))
}

// ProfitEQ applies the EQ predicate on the "profit" field.
func ProfitEQ(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldProfit, v))
}

// ProfitNEQ applies the NEQ predicate on the "profit" field.
func ProfitNEQ(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldProfit, v))
}

// ProfitIn applies the In predicate on the "profit" field.
func ProfitIn(vs ...float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldProfit, vs...))
}

// ProfitNotIn applies the NotIn predicate on the "profit" field.
func ProfitNotIn(vs ...float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldProfit, vs...))
}

// ProfitGT applies the GT predicate on the "profit" field.
func ProfitGT(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldProfit, v))
}

// ProfitGTE applies the GTE predicate on the "profit" field.
func ProfitGTE(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldProfit, v))
}

// ProfitLT applies the LT predicate on the "profit" field.
func ProfitLT(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldProfit, v))
}

// ProfitLTE applies the LTE predicate on the "profit" field.
func ProfitLTE(v float64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldProfit, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldOccurredAt, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldContainsFold(FieldNote, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.FieldLTE(FieldCreatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AdminBillingRecord) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AdminBillingRecord) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AdminBillingRecord) predicate.AdminBillingRecord {
	return predicate.AdminBillingRecord(sql.NotPredicates(p))
}
