// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adminbillingrecord"
)

// AdminBillingRecordCreate is the builder for creating a AdminBillingRecord entity.
type AdminBillingRecordCreate struct {
	config
	mutation *AdminBillingRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminBillingRecordCreate) SetCreatedAt(v time.Time) *AdminBillingRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminBillingRecordCreate) SetNillableCreatedAt(v *time.Time) *AdminBillingRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdminBillingRecordCreate) SetUpdatedAt(v time.Time) *AdminBillingRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdminBillingRecordCreate) SetNillableUpdatedAt(v *time.Time) *AdminBillingRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AdminBillingRecordCreate) SetDeletedAt(v time.Time) *AdminBillingRecordCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AdminBillingRecordCreate) SetNillableDeletedAt(v *time.Time) *AdminBillingRecordCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetPersonName sets the "person_name" field.
func (_c *AdminBillingRecordCreate) SetPersonName(v string) *AdminBillingRecordCreate {
	_c.mutation.SetPersonName(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *AdminBillingRecordCreate) SetSource(v string) *AdminBillingRecordCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *AdminBillingRecordCreate) SetNillableSource(v *string) *AdminBillingRecordCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *AdminBillingRecordCreate) SetCost(v float64) *AdminBillingRecordCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *AdminBillingRecordCreate) SetNillableCost(v *float64) *AdminBillingRecordCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetProfit sets the "profit" field.
func (_c *AdminBillingRecordCreate) SetProfit(v float64) *AdminBillingRecordCreate {
	_c.mutation.SetProfit(v)
	return _c
}

// SetNillableProfit sets the "profit" field if the given value is not nil.
func (_c *AdminBillingRecordCreate) SetNillableProfit(v *float64) *AdminBillingRecordCreate {
	if v != nil {
		_c.SetProfit(*v)
	}
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *AdminBillingRecordCreate) SetOccurredAt(v time.Time) *AdminBillingRecordCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_c *AdminBillingRecordCreate) SetNillableOccurredAt(v *time.Time) *AdminBillingRecordCreate {
	if v != nil {
		_c.SetOccurredAt(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *AdminBillingRecordCreate) SetNote(v string) *AdminBillingRecordCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *AdminBillingRecordCreate) SetNillableNote(v *string) *AdminBillingRecordCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *AdminBillingRecordCreate) SetCreatedBy(v int64) *AdminBillingRecordCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// Mutation returns the AdminBillingRecordMutation object of the builder.
func (_c *AdminBillingRecordCreate) Mutation() *AdminBillingRecordMutation {
	return _c.mutation
}

// Save creates the AdminBillingRecord in the database.
func (_c *AdminBillingRecordCreate) Save(ctx context.Context) (*AdminBillingRecord, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminBillingRecordCreate) SaveX(ctx context.Context) *AdminBillingRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminBillingRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminBillingRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminBillingRecordCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if adminbillingrecord.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized adminbillingrecord.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := adminbillingrecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if adminbillingrecord.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized adminbillingrecord.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := adminbillingrecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := adminbillingrecord.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Cost(); !ok {
		v := adminbillingrecord.DefaultCost
		_c.mutation.SetCost(v)
	}
	if _, ok := _c.mutation.Profit(); !ok {
		v := adminbillingrecord.DefaultProfit
		_c.mutation.SetProfit(v)
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		if adminbillingrecord.DefaultOccurredAt == nil {
			return fmt.Errorf("ent: uninitialized adminbillingrecord.DefaultOccurredAt (forgotten import ent/runtime?)")
		}
		v := adminbillingrecord.DefaultOccurredAt()
		_c.mutation.SetOccurredAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminBillingRecordCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminBillingRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdminBillingRecord.updated_at"`)}
	}
	if _, ok := _c.mutation.PersonName(); !ok {
		return &ValidationError{Name: "person_name", err: errors.New(`ent: missing required field "AdminBillingRecord.person_name"`)}
	}
	if v, ok := _c.mutation.PersonName(); ok {
		if err := adminbillingrecord.PersonNameValidator(v); err != nil {
			return &ValidationError{Name: "person_name", err: fmt.Errorf(`ent: validator failed for field "AdminBillingRecord.person_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "AdminBillingRecord.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := adminbillingrecord.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "AdminBillingRecord.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "AdminBillingRecord.cost"`)}
	}
	if _, ok := _c.mutation.Profit(); !ok {
		return &ValidationError{Name: "profit", err: errors.New(`ent: missing required field "AdminBillingRecord.profit"`)}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "AdminBillingRecord.occurred_at"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "AdminBillingRecord.created_by"`)}
	}
	return nil
}

func (_c *AdminBillingRecordCreate) sqlSave(ctx context.Context) (*AdminBillingRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminBillingRecordCreate) createSpec() (*AdminBillingRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminBillingRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminbillingrecord.Table, sqlgraph.NewFieldSpec(adminbillingrecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminbillingrecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adminbillingrecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(adminbillingrecord.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.PersonName(); ok {
		_spec.SetField(adminbillingrecord.FieldPersonName, field.TypeString, value)
		_node.PersonName = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(adminbillingrecord.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(adminbillingrecord.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.Profit(); ok {
		_spec.SetField(adminbillingrecord.FieldProfit, field.TypeFloat64, value)
		_node.Profit = value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(adminbillingrecord.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(adminbillingrecord.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(adminbillingrecord.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminBillingRecord.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminBillingRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminBillingRecordCreate) OnConflict(opts ...sql.ConflictOption) *AdminBillingRecordUpsertOne {
	_c.conflict = opts
	return &AdminBillingRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminBillingRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminBillingRecordCreate) OnConflictColumns(columns ...string) *AdminBillingRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminBillingRecordUpsertOne{
		create: _c,
	}
}

type (
	// AdminBillingRecordUpsertOne is the builder for "upsert"-ing
	//  one AdminBillingRecord node.
	AdminBillingRecordUpsertOne struct {
		create *AdminBillingRecordCreate
	}

	// AdminBillingRecordUpsert is the "OnConflict" setter.
	AdminBillingRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AdminBillingRecordUpsert) SetUpdatedAt(v time.Time) *AdminBillingRecordUpsert {
	u.Set(adminbillingrecord.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdminBillingRecordUpsert) UpdateUpdatedAt() *AdminBillingRecordUpsert {
	u.SetExcluded(adminbillingrecord.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AdminBillingRecordUpsert) SetDeletedAt(v time.Time) *AdminBillingRecordUpsert {
	u.Set(adminbillingrecord.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AdminBillingRecordUpsert) UpdateDeletedAt() *AdminBillingRecordUpsert {
	u.SetExcluded(adminbillingrecord.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AdminBillingRecordUpsert) ClearDeletedAt() *AdminBillingRecordUpsert {
	u.SetNull(adminbillingrecord.FieldDeletedAt)
	return u
}

// SetPersonName sets the "person_name" field.
func (u *AdminBillingRecordUpsert) SetPersonName(v string) *AdminBillingRecordUpsert {
	u.Set(adminbillingrecord.FieldPersonName, v)
	return u
}

// UpdatePersonName sets the "person_name" field to the value that was provided on create.
func (u *AdminBillingRecordUpsert) UpdatePersonName() *AdminBillingRecordUpsert {
	u.SetExcluded(adminbillingrecord.FieldPersonName)
	return u
}

// SetSource sets the "source" field.
func (u *AdminBillingRecordUpsert) SetSource(v string) *AdminBillingRecordUpsert {
	u.Set(adminbillingrecord.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AdminBillingRecordUpsert) UpdateSource() *AdminBillingRecordUpsert {
	u.SetExcluded(adminbillingrecord.FieldSource)
	return u
}

// SetCost sets the "cost" field.
func (u *AdminBillingRecordUpsert) SetCost(v float64) *AdminBillingRecordUpsert {
	u.Set(adminbillingrecord.FieldCost, v)
	return u
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *AdminBillingRecordUpsert) UpdateCost() *AdminBillingRecordUpsert {
	u.SetExcluded(adminbillingrecord.FieldCost)
	return u
}

// AddCost adds v to the "cost" field.
func (u *AdminBillingRecordUpsert) AddCost(v float64) *AdminBillingRecordUpsert {
	u.Add(adminbillingrecord.FieldCost, v)
	return u
}

// SetProfit sets the "profit" field.
func (u *AdminBillingRecordUpsert) SetProfit(v float64) *AdminBillingRecordUpsert {
	u.Set(adminbillingrecord.FieldProfit, v)
	return u
}

// UpdateProfit sets the "profit" field to the value that was provided on create.
func (u *AdminBillingRecordUpsert) UpdateProfit() *AdminBillingRecordUpsert {
	u.SetExcluded(adminbillingrecord.FieldProfit)
	return u
}

// AddProfit adds v to the "profit" field.
func (u *AdminBillingRecordUpsert) AddProfit(v float64) *AdminBillingRecordUpsert {
	u.Add(adminbillingrecord.FieldProfit, v)
	return u
}

// SetOccurredAt sets the "occurred_at" field.
func (u *AdminBillingRecordUpsert) SetOccurredAt(v time.Time) *AdminBillingRecordUpsert {
	u.Set(adminbillingrecord.FieldOccurredAt, v)
	return u
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *AdminBillingRecordUpsert) UpdateOccurredAt() *AdminBillingRecordUpsert {
	u.SetExcluded(adminbillingrecord.FieldOccurredAt)
	return u
}

// SetNote sets the "note" field.
func (u *AdminBillingRecordUpsert) SetNote(v string) *AdminBillingRecordUpsert {
	u.Set(adminbillingrecord.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *AdminBillingRecordUpsert) UpdateNote() *AdminBillingRecordUpsert {
	u.SetExcluded(adminbillingrecord.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *AdminBillingRecordUpsert) ClearNote() *AdminBillingRecordUpsert {
	u.SetNull(adminbillingrecord.FieldNote)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *AdminBillingRecordUpsert) SetCreatedBy(v int64) *AdminBillingRecordUpsert {
	u.Set(adminbillingrecord.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AdminBillingRecordUpsert) UpdateCreatedBy() *AdminBillingRecordUpsert {
	u.SetExcluded(adminbillingrecord.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AdminBillingRecordUpsert) AddCreatedBy(v int64) *AdminBillingRecordUpsert {
	u.Add(adminbillingrecord.FieldCreatedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AdminBillingRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminBillingRecordUpsertOne) UpdateNewValues() *AdminBillingRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(adminbillingrecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminBillingRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdminBillingRecordUpsertOne) Ignore() *AdminBillingRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminBillingRecordUpsertOne) DoNothing() *AdminBillingRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminBillingRecordCreate.OnConflict
// documentation for more info.
func (u *AdminBillingRecordUpsertOne) Update(set func(*AdminBillingRecordUpsert)) *AdminBillingRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminBillingRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdminBillingRecordUpsertOne) SetUpdatedAt(v time.Time) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertOne) UpdateUpdatedAt() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AdminBillingRecordUpsertOne) SetDeletedAt(v time.Time) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertOne) UpdateDeletedAt() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AdminBillingRecordUpsertOne) ClearDeletedAt() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.ClearDeletedAt()
	})
}

// SetPersonName sets the "person_name" field.
func (u *AdminBillingRecordUpsertOne) SetPersonName(v string) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetPersonName(v)
	})
}

// UpdatePersonName sets the "person_name" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertOne) UpdatePersonName() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdatePersonName()
	})
}

// SetSource sets the "source" field.
func (u *AdminBillingRecordUpsertOne) SetSource(v string) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertOne) UpdateSource() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateSource()
	})
}

// SetCost sets the "cost" field.
func (u *AdminBillingRecordUpsertOne) SetCost(v float64) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *AdminBillingRecordUpsertOne) AddCost(v float64) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertOne) UpdateCost() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateCost()
	})
}

// SetProfit sets the "profit" field.
func (u *AdminBillingRecordUpsertOne) SetProfit(v float64) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetProfit(v)
	})
}

// AddProfit adds v to the "profit" field.
func (u *AdminBillingRecordUpsertOne) AddProfit(v float64) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.AddProfit(v)
	})
}

// UpdateProfit sets the "profit" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertOne) UpdateProfit() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateProfit()
	})
}

// SetOccurredAt sets the "occurred_at" field.
func (u *AdminBillingRecordUpsertOne) SetOccurredAt(v time.Time) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetOccurredAt(v)
	})
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertOne) UpdateOccurredAt() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateOccurredAt()
	})
}

// SetNote sets the "note" field.
func (u *AdminBillingRecordUpsertOne) SetNote(v string) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertOne) UpdateNote() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *AdminBillingRecordUpsertOne) ClearNote() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.ClearNote()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AdminBillingRecordUpsertOne) SetCreatedBy(v int64) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AdminBillingRecordUpsertOne) AddCreatedBy(v int64) *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertOne) UpdateCreatedBy() *AdminBillingRecordUpsertOne {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *AdminBillingRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminBillingRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminBillingRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdminBillingRecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdminBillingRecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdminBillingRecordCreateBulk is the builder for creating many AdminBillingRecord entities in bulk.
type AdminBillingRecordCreateBulk struct {
	config
	err      error
	builders []*AdminBillingRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the AdminBillingRecord entities in the database.
func (_c *AdminBillingRecordCreateBulk) Save(ctx context.Context) ([]*AdminBillingRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminBillingRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminBillingRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminBillingRecordCreateBulk) SaveX(ctx context.Context) []*AdminBillingRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminBillingRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminBillingRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AdminBillingRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdminBillingRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AdminBillingRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdminBillingRecordUpsertBulk {
	_c.conflict = opts
	return &AdminBillingRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AdminBillingRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AdminBillingRecordCreateBulk) OnConflictColumns(columns ...string) *AdminBillingRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AdminBillingRecordUpsertBulk{
		create: _c,
	}
}

// AdminBillingRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of AdminBillingRecord nodes.
type AdminBillingRecordUpsertBulk struct {
	create *AdminBillingRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AdminBillingRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AdminBillingRecordUpsertBulk) UpdateNewValues() *AdminBillingRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(adminbillingrecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AdminBillingRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdminBillingRecordUpsertBulk) Ignore() *AdminBillingRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdminBillingRecordUpsertBulk) DoNothing() *AdminBillingRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdminBillingRecordCreateBulk.OnConflict
// documentation for more info.
func (u *AdminBillingRecordUpsertBulk) Update(set func(*AdminBillingRecordUpsert)) *AdminBillingRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdminBillingRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AdminBillingRecordUpsertBulk) SetUpdatedAt(v time.Time) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertBulk) UpdateUpdatedAt() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AdminBillingRecordUpsertBulk) SetDeletedAt(v time.Time) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertBulk) UpdateDeletedAt() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AdminBillingRecordUpsertBulk) ClearDeletedAt() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.ClearDeletedAt()
	})
}

// SetPersonName sets the "person_name" field.
func (u *AdminBillingRecordUpsertBulk) SetPersonName(v string) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetPersonName(v)
	})
}

// UpdatePersonName sets the "person_name" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertBulk) UpdatePersonName() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdatePersonName()
	})
}

// SetSource sets the "source" field.
func (u *AdminBillingRecordUpsertBulk) SetSource(v string) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertBulk) UpdateSource() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateSource()
	})
}

// SetCost sets the "cost" field.
func (u *AdminBillingRecordUpsertBulk) SetCost(v float64) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *AdminBillingRecordUpsertBulk) AddCost(v float64) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertBulk) UpdateCost() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateCost()
	})
}

// SetProfit sets the "profit" field.
func (u *AdminBillingRecordUpsertBulk) SetProfit(v float64) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetProfit(v)
	})
}

// AddProfit adds v to the "profit" field.
func (u *AdminBillingRecordUpsertBulk) AddProfit(v float64) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.AddProfit(v)
	})
}

// UpdateProfit sets the "profit" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertBulk) UpdateProfit() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateProfit()
	})
}

// SetOccurredAt sets the "occurred_at" field.
func (u *AdminBillingRecordUpsertBulk) SetOccurredAt(v time.Time) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetOccurredAt(v)
	})
}

// UpdateOccurredAt sets the "occurred_at" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertBulk) UpdateOccurredAt() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateOccurredAt()
	})
}

// SetNote sets the "note" field.
func (u *AdminBillingRecordUpsertBulk) SetNote(v string) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertBulk) UpdateNote() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *AdminBillingRecordUpsertBulk) ClearNote() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.ClearNote()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *AdminBillingRecordUpsertBulk) SetCreatedBy(v int64) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *AdminBillingRecordUpsertBulk) AddCreatedBy(v int64) *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *AdminBillingRecordUpsertBulk) UpdateCreatedBy() *AdminBillingRecordUpsertBulk {
	return u.Update(func(s *AdminBillingRecordUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *AdminBillingRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdminBillingRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdminBillingRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdminBillingRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
