// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/adminbillingrecord"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AdminBillingRecordUpdate is the builder for updating AdminBillingRecord entities.
type AdminBillingRecordUpdate struct {
	config
	hooks    []Hook
	mutation *AdminBillingRecordMutation
}

// Where appends a list predicates to the AdminBillingRecordUpdate builder.
func (_u *AdminBillingRecordUpdate) Where(ps ...predicate.AdminBillingRecord) *AdminBillingRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminBillingRecordUpdate) SetUpdatedAt(v time.Time) *AdminBillingRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AdminBillingRecordUpdate) SetDeletedAt(v time.Time) *AdminBillingRecordUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AdminBillingRecordUpdate) SetNillableDeletedAt(v *time.Time) *AdminBillingRecordUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AdminBillingRecordUpdate) ClearDeletedAt() *AdminBillingRecordUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPersonName sets the "person_name" field.
func (_u *AdminBillingRecordUpdate) SetPersonName(v string) *AdminBillingRecordUpdate {
	_u.mutation.SetPersonName(v)
	return _u
}

// SetNillablePersonName sets the "person_name" field if the given value is not nil.
func (_u *AdminBillingRecordUpdate) SetNillablePersonName(v *string) *AdminBillingRecordUpdate {
	if v != nil {
		_u.SetPersonName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *AdminBillingRecordUpdate) SetSource(v string) *AdminBillingRecordUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AdminBillingRecordUpdate) SetNillableSource(v *string) *AdminBillingRecordUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCost sets the "cost" field.
func (_u *AdminBillingRecordUpdate) SetCost(v float64) *AdminBillingRecordUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *AdminBillingRecordUpdate) SetNillableCost(v *float64) *AdminBillingRecordUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *AdminBillingRecordUpdate) AddCost(v float64) *AdminBillingRecordUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// SetProfit sets the "profit" field.
func (_u *AdminBillingRecordUpdate) SetProfit(v float64) *AdminBillingRecordUpdate {
	_u.mutation.ResetProfit()
	_u.mutation.SetProfit(v)
	return _u
}

// SetNillableProfit sets the "profit" field if the given value is not nil.
func (_u *AdminBillingRecordUpdate) SetNillableProfit(v *float64) *AdminBillingRecordUpdate {
	if v != nil {
		_u.SetProfit(*v)
	}
	return _u
}

// AddProfit adds value to the "profit" field.
func (_u *AdminBillingRecordUpdate) AddProfit(v float64) *AdminBillingRecordUpdate {
	_u.mutation.AddProfit(v)
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *AdminBillingRecordUpdate) SetOccurredAt(v time.Time) *AdminBillingRecordUpdate {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *AdminBillingRecordUpdate) SetNillableOccurredAt(v *time.Time) *AdminBillingRecordUpdate {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *AdminBillingRecordUpdate) SetNote(v string) *AdminBillingRecordUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *AdminBillingRecordUpdate) SetNillableNote(v *string) *AdminBillingRecordUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *AdminBillingRecordUpdate) ClearNote() *AdminBillingRecordUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AdminBillingRecordUpdate) SetCreatedBy(v int64) *AdminBillingRecordUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AdminBillingRecordUpdate) SetNillableCreatedBy(v *int64) *AdminBillingRecordUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AdminBillingRecordUpdate) AddCreatedBy(v int64) *AdminBillingRecordUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// Mutation returns the AdminBillingRecordMutation object of the builder.
func (_u *AdminBillingRecordUpdate) Mutation() *AdminBillingRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminBillingRecordUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminBillingRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminBillingRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminBillingRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminBillingRecordUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if adminbillingrecord.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized adminbillingrecord.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := adminbillingrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminBillingRecordUpdate) check() error {
	if v, ok := _u.mutation.PersonName(); ok {
		if err := adminbillingrecord.PersonNameValidator(v); err != nil {
			return &ValidationError{Name: "person_name", err: fmt.Errorf(`ent: validator failed for field "AdminBillingRecord.person_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := adminbillingrecord.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "AdminBillingRecord.source": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminBillingRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminbillingrecord.Table, adminbillingrecord.Columns, sqlgraph.NewFieldSpec(adminbillingrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminbillingrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(adminbillingrecord.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(adminbillingrecord.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PersonName(); ok {
		_spec.SetField(adminbillingrecord.FieldPersonName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(adminbillingrecord.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(adminbillingrecord.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(adminbillingrecord.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Profit(); ok {
		_spec.SetField(adminbillingrecord.FieldProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfit(); ok {
		_spec.AddField(adminbillingrecord.FieldProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(adminbillingrecord.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(adminbillingrecord.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(adminbillingrecord.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(adminbillingrecord.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(adminbillingrecord.FieldCreatedBy, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminbillingrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminBillingRecordUpdateOne is the builder for updating a single AdminBillingRecord entity.
type AdminBillingRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminBillingRecordMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AdminBillingRecordUpdateOne) SetUpdatedAt(v time.Time) *AdminBillingRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AdminBillingRecordUpdateOne) SetDeletedAt(v time.Time) *AdminBillingRecordUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AdminBillingRecordUpdateOne) SetNillableDeletedAt(v *time.Time) *AdminBillingRecordUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AdminBillingRecordUpdateOne) ClearDeletedAt() *AdminBillingRecordUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPersonName sets the "person_name" field.
func (_u *AdminBillingRecordUpdateOne) SetPersonName(v string) *AdminBillingRecordUpdateOne {
	_u.mutation.SetPersonName(v)
	return _u
}

// SetNillablePersonName sets the "person_name" field if the given value is not nil.
func (_u *AdminBillingRecordUpdateOne) SetNillablePersonName(v *string) *AdminBillingRecordUpdateOne {
	if v != nil {
		_u.SetPersonName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *AdminBillingRecordUpdateOne) SetSource(v string) *AdminBillingRecordUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *AdminBillingRecordUpdateOne) SetNillableSource(v *string) *AdminBillingRecordUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetCost sets the "cost" field.
func (_u *AdminBillingRecordUpdateOne) SetCost(v float64) *AdminBillingRecordUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *AdminBillingRecordUpdateOne) SetNillableCost(v *float64) *AdminBillingRecordUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *AdminBillingRecordUpdateOne) AddCost(v float64) *AdminBillingRecordUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// SetProfit sets the "profit" field.
func (_u *AdminBillingRecordUpdateOne) SetProfit(v float64) *AdminBillingRecordUpdateOne {
	_u.mutation.ResetProfit()
	_u.mutation.SetProfit(v)
	return _u
}

// SetNillableProfit sets the "profit" field if the given value is not nil.
func (_u *AdminBillingRecordUpdateOne) SetNillableProfit(v *float64) *AdminBillingRecordUpdateOne {
	if v != nil {
		_u.SetProfit(*v)
	}
	return _u
}

// AddProfit adds value to the "profit" field.
func (_u *AdminBillingRecordUpdateOne) AddProfit(v float64) *AdminBillingRecordUpdateOne {
	_u.mutation.AddProfit(v)
	return _u
}

// SetOccurredAt sets the "occurred_at" field.
func (_u *AdminBillingRecordUpdateOne) SetOccurredAt(v time.Time) *AdminBillingRecordUpdateOne {
	_u.mutation.SetOccurredAt(v)
	return _u
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_u *AdminBillingRecordUpdateOne) SetNillableOccurredAt(v *time.Time) *AdminBillingRecordUpdateOne {
	if v != nil {
		_u.SetOccurredAt(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *AdminBillingRecordUpdateOne) SetNote(v string) *AdminBillingRecordUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *AdminBillingRecordUpdateOne) SetNillableNote(v *string) *AdminBillingRecordUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *AdminBillingRecordUpdateOne) ClearNote() *AdminBillingRecordUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *AdminBillingRecordUpdateOne) SetCreatedBy(v int64) *AdminBillingRecordUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *AdminBillingRecordUpdateOne) SetNillableCreatedBy(v *int64) *AdminBillingRecordUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *AdminBillingRecordUpdateOne) AddCreatedBy(v int64) *AdminBillingRecordUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// Mutation returns the AdminBillingRecordMutation object of the builder.
func (_u *AdminBillingRecordUpdateOne) Mutation() *AdminBillingRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminBillingRecordUpdate builder.
func (_u *AdminBillingRecordUpdateOne) Where(ps ...predicate.AdminBillingRecord) *AdminBillingRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminBillingRecordUpdateOne) Select(field string, fields ...string) *AdminBillingRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminBillingRecord entity.
func (_u *AdminBillingRecordUpdateOne) Save(ctx context.Context) (*AdminBillingRecord, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminBillingRecordUpdateOne) SaveX(ctx context.Context) *AdminBillingRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminBillingRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminBillingRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdminBillingRecordUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if adminbillingrecord.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized adminbillingrecord.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := adminbillingrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminBillingRecordUpdateOne) check() error {
	if v, ok := _u.mutation.PersonName(); ok {
		if err := adminbillingrecord.PersonNameValidator(v); err != nil {
			return &ValidationError{Name: "person_name", err: fmt.Errorf(`ent: validator failed for field "AdminBillingRecord.person_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := adminbillingrecord.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "AdminBillingRecord.source": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminBillingRecordUpdateOne) sqlSave(ctx context.Context) (_node *AdminBillingRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminbillingrecord.Table, adminbillingrecord.Columns, sqlgraph.NewFieldSpec(adminbillingrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminBillingRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminbillingrecord.FieldID)
		for _, f := range fields {
			if !adminbillingrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminbillingrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(adminbillingrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(adminbillingrecord.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(adminbillingrecord.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PersonName(); ok {
		_spec.SetField(adminbillingrecord.FieldPersonName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(adminbillingrecord.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(adminbillingrecord.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(adminbillingrecord.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Profit(); ok {
		_spec.SetField(adminbillingrecord.FieldProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProfit(); ok {
		_spec.AddField(adminbillingrecord.FieldProfit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OccurredAt(); ok {
		_spec.SetField(adminbillingrecord.FieldOccurredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(adminbillingrecord.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(adminbillingrecord.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(adminbillingrecord.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(adminbillingrecord.FieldCreatedBy, field.TypeInt64, value)
	}
	_node = &AdminBillingRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminbillingrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
