// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/adminbillingrecord"
)

// AdminBillingRecord is the model entity for the AdminBillingRecord schema.
type AdminBillingRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 记账归属人名（自由文本，不关联 users）
	PersonName string `json:"person_name,omitempty"`
	// 订单来源（自由文本，内置微信/咸鱼/淘宝，可自定义）
	Source string `json:"source,omitempty"`
	// 成本
	Cost float64 `json:"cost,omitempty"`
	// 利润
	Profit float64 `json:"profit,omitempty"`
	// 业务发生日期（可由管理员指定，默认 now）
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// 备注
	Note *string `json:"note,omitempty"`
	// 创建该记录的管理员用户 ID（审计）
	CreatedBy    int64 `json:"created_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdminBillingRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case adminbillingrecord.FieldCost, adminbillingrecord.FieldProfit:
			values[i] = new(sql.NullFloat64)
		case adminbillingrecord.FieldID, adminbillingrecord.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case adminbillingrecord.FieldPersonName, adminbillingrecord.FieldSource, adminbillingrecord.FieldNote:
			values[i] = new(sql.NullString)
		case adminbillingrecord.FieldCreatedAt, adminbillingrecord.FieldUpdatedAt, adminbillingrecord.FieldDeletedAt, adminbillingrecord.FieldOccurredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdminBillingRecord fields.
func (_m *AdminBillingRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adminbillingrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case adminbillingrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case adminbillingrecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case adminbillingrecord.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case adminbillingrecord.FieldPersonName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field person_name", values[i])
			} else if value.Valid {
				_m.PersonName = value.String
			}
		case adminbillingrecord.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case adminbillingrecord.FieldCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost", values[i])
			} else if value.Valid {
				_m.Cost = value.Float64
			}
		case adminbillingrecord.FieldProfit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field profit", values[i])
			} else if value.Valid {
				_m.Profit = value.Float64
			}
		case adminbillingrecord.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				_m.OccurredAt = value.Time
			}
		case adminbillingrecord.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		case adminbillingrecord.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AdminBillingRecord.
// This includes values selected through modifiers, order, etc.
func (_m *AdminBillingRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AdminBillingRecord.
// Note that you need to call AdminBillingRecord.Unwrap() before calling this method if this AdminBillingRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AdminBillingRecord) Update() *AdminBillingRecordUpdateOne {
	return NewAdminBillingRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AdminBillingRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AdminBillingRecord) Unwrap() *AdminBillingRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdminBillingRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AdminBillingRecord) String() string {
	var builder strings.Builder
	builder.WriteString("AdminBillingRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("person_name=")
	builder.WriteString(_m.PersonName)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cost))
	builder.WriteString(", ")
	builder.WriteString("profit=")
	builder.WriteString(fmt.Sprintf("%v", _m.Profit))
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(_m.OccurredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteByte(')')
	return builder.String()
}

// AdminBillingRecords is a parsable slice of AdminBillingRecord.
type AdminBillingRecords []*AdminBillingRecord
